name: Deployment

concurrency: production

on:
  push:
    tags:
      - "v[12].[0-9]+.[0-9]+"

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installing Deps
        run: yarn --frozen-lockfile

      - name: Testing
        run: yarn test:run

      - name: Building
        run: yarn build

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
