name: Deployment

concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v[12].[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Installing Deps
        run: yarn --frozen-lockfile

      - name: Linting
        run: yarn lint:check

      - name: Testing
        run: yarn test:run

      - name: Building
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
