name: Deployment

concurrency: production

on:
  push:
    tags:
      - 'v[12].[0-9]+.[0-9]+'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing Deps
        run: yarn --frozen-lockfile

      - name: Linting
        run: yarn lint:check

      - name: Testing
        run: yarn test:run

      - name: Building
        run: yarn build

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
