name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]
  
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
      
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Installing Deps
        run: yarn --frozen-lockfile
      
      - name: Testing
        run: yarn test:run
      
      - name: Building
        run: yarn build